name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
        

    steps:
    - uses: actions/checkout@v2
      with: 
        token: ${{secrets.GHCR_LOGIN}}

    - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      run: docker build -t ghcr.io/djnotes/madelineproto:latest .
    - name: Authenticate in the Workflow
      run:  docker login ghcr.io --username djnotes --password "$GHCR_LOGIN"
    - name: Push the Docker image
      run: docker push ghcr.io/djnotes/madelineproto:latest
